FROM devopsfaith/krakend as krakend

USER root

ENV REGION
ENV ENVIRONMENT

ENV FC_ENABLE=1
ENV FC_SETTINGS=/etc/krakend/config/settings/${ENVIRONMENT}/${REGION}
ENV FC_PARTIALS=/etc/krakend/config/partials
ENV FC_TEMPLATES=/etc/krakend/config/templates

RUN mkdir /etc/krakend/config
COPY config/ /etc/krakend/config/
COPY krakend.json/ /etc/krakend/krakend.json

ENTRYPOINT ["/usr/bin/krakend", "check", "-c", "/etc/krakend/krakend.json"]
