name: Validate KrakenD config file

on:
  push:

jobs:
  # build-validate:
  #   runs-on: ubuntu-latest
  #   steps:

  run-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        regions: ["global", "uk"]
        environment: ["landing-zone", "stage"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t validate -f Dockerfile.validate .
      - name: Log envs
        env:
          REGION: ${{ matrix.regions }}
          ENVIRONMENT: ${{ matrix.environment }}
        run: echo $REGION $ENVIRONMENT
      - name: Run validation
        env:
          REGION: ${{ matrix.regions }}
          ENVIRONMENT: ${{ matrix.environment }}
        run: docker run -e REGION=$REGION -e ENVIRONMENT=$ENVIRONMENT validate
